import { Injectable } from '@angular/core';
import { DepartamentoI, CiudadI } from '../modelos/ciudades';



@Injectable({
  providedIn: 'root'
})
export class DepartamentosService {


  constructor() { }


  public departamentos: DepartamentoI[] = [
    {
      id: 1,
      name: 'Amazonas'
    },
    {
      id: 2,
      name: 'Antioquia'
    },
    {
      id: 3,
      name: 'Arauca'
    },
    {
      id: 4,
      name: 'Atlántico'
    },
    {
      id: 5,
      name: 'Bogotá, D.C'
    },
    {
      id: 6,
      name: 'Bolívar'
    },
    {
      id: 7,
      name: 'Boyacá'
    },
    {
      id: 8,
      name: 'Caldas'
    },
    {
      id: 9,
      name: 'Caquetá'
    },
    {
      id: 10,
      name: 'Casanare'
    },
    {
      id: 11,
      name: 'Cauca'
    },
    {
      id: 12,
      name: 'Cesar'
    },
    {
      id: 13,
      name: 'Chocó'
    },
    {
      id: 14,
      name: 'Córdoba'
    },
    {
      id: 15,
      name: 'Cundinamarca'
    },
    {
      id: 16,
      name: 'Guainía'
    },
    {
      id: 17,
      name: 'Guaviare'
    },
    {
      id: 18,
      name: 'Huilda'
    },
    {
      id: 19,
      name: 'La Guajita'
    },
    {
      id: 20,
      name: 'Magdalena'
    },
    {
      id: 21,
      name: 'Meta'
    },
    {
      id: 22,
      name: 'Nariño'
    },
    {
      id: 23,
      name: 'Norte de Santander'
    },
    {
      id: 24,
      name: 'Putumayo'
    },
    {
      id: 25,
      name: 'Quindío'
    },
    {
      id: 26,
      name: 'Risaralda'
    },
    {
      id: 27,
      name: 'San Andrés y Providencia'
    },
    {
      id: 28,
      name: 'Santander'
    },
    {
      id: 29,
      name: 'Sucre'
    },
    {
      id: 30,
      name: 'Tolima'
    },
    {
      id: 31,
      name: 'Valle del Cauca'
    },
    {
      id: 32,
      name: 'Vaupés'
    },
    {
      id: 33,
      name: 'Vichada'
    }
  ]

  public ciudades: CiudadI[] = [
    { id: 1, departamentoId: 1, name: ' Puerto Alegria' },
    { id: 2, departamentoId: 1, name: ' La chorrera' },
    { id: 3, departamentoId: 1, name: ' Puerto Santander' },
    { id: 4, departamentoId: 1, name: ' Miriti-Parana' },
    { id: 5, departamentoId: 1, name: ' La Victoria' },
    { id: 6, departamentoId: 1, name: ' La pedrera' },
    { id: 7, departamentoId: 1, name: ' Puerto Arica' },
    { id: 8, departamentoId: 1, name: ' El Encanto' },
    { id: 9, departamentoId: 1, name: ' Tarapacá' },
    { id: 10, departamentoId: 1, name: ' Leticia' },
    { id: 11, departamentoId: 1, name: ' Puerto Nariño' },


    { id: 1, departamentoId: 2, name: ' Cáceres ' },
    { id: 2, departamentoId: 2, name: ' Caucasia ' },
    { id: 3, departamentoId: 2, name: ' El Bagre ' },
    { id: 4, departamentoId: 2, name: ' Nechí ' },
    { id: 5, departamentoId: 2, name: ' Tarazá ' },
    { id: 6, departamentoId: 2, name: ' Zaragoza ' },
    { id: 7, departamentoId: 2, name: ' Caracolí ' },
    { id: 8, departamentoId: 2, name: ' Maceo ' },
    { id: 9, departamentoId: 2, name: ' Puerto Berrío ' },
    { id: 10, departamentoId: 2, name: ' Puerto Nare ' },
    { id: 11, departamentoId: 2, name: ' Puerto Triunfo ' },
    { id: 12, departamentoId: 2, name: ' Yondó ' },
    { id: 13, departamentoId: 2, name: ' Amalfi ' },
    { id: 14, departamentoId: 2, name: ' Anorí ' },
    { id: 15, departamentoId: 2, name: ' Cisneros ' },
    { id: 16, departamentoId: 2, name: ' Remedios ' },
    { id: 17, departamentoId: 2, name: ' San Roque ' },
    { id: 18, departamentoId: 2, name: ' Santo Domingo ' },
    { id: 19, departamentoId: 2, name: ' Segovia ' },
    { id: 20, departamentoId: 2, name: ' Vegachí ' },
    { id: 21, departamentoId: 2, name: ' Yalí ' },
    { id: 22, departamentoId: 2, name: ' Yolombó ' },
    { id: 23, departamentoId: 1, name: ' Angostura ' },
    { id: 24, departamentoId: 2, name: ' Belmira ' },
    { id: 25, departamentoId: 2, name: ' Briceño ' },
    { id: 26, departamentoId: 2, name: ' Campamento ' },
    { id: 27, departamentoId: 2, name: ' Carolina del Príncipe ' },
    { id: 28, departamentoId: 2, name: ' Donmatías ' },
    { id: 29, departamentoId: 2, name: ' Entrerríos ' },
    { id: 30, departamentoId: 2, name: ' Gómez Plata ' },
    { id: 31, departamentoId: 2, name: ' Guadalupe ' },
    { id: 32, departamentoId: 2, name: ' Ituango ' },
    { id: 33, departamentoId: 2, name: ' San Andrés de Cuerquia ' },
    { id: 34, departamentoId: 2, name: ' San José de la Montaña ' },
    { id: 35, departamentoId: 2, name: ' San Pedro de los Milagros ' },
    { id: 36, departamentoId: 2, name: ' Santa Rosa de Osos ' },
    { id: 37, departamentoId: 2, name: ' Toledo ' },
    { id: 38, departamentoId: 2, name: ' Valdivia ' },
    { id: 39, departamentoId: 2, name: ' Yarumal ' },
    { id: 40, departamentoId: 2, name: ' Abriaquí ' },
    { id: 41, departamentoId: 2, name: ' Santa Fe de Antioquia ' },
    { id: 42, departamentoId: 2, name: ' Anzá ' },
    { id: 43, departamentoId: 2, name: ' Armenia ' },
    { id: 44, departamentoId: 2, name: ' Buriticá ' },
    { id: 45, departamentoId: 2, name: ' Caicedo ' },
    { id: 46, departamentoId: 2, name: ' Cañasgordas ' },
    { id: 47, departamentoId: 2, name: ' Dabeiba ' },
    { id: 48, departamentoId: 2, name: ' Ebéjico ' },
    { id: 49, departamentoId: 2, name: ' Frontino ' },
    { id: 50, departamentoId: 2, name: ' Giraldo ' },
    { id: 51, departamentoId: 2, name: ' Heliconia ' },
    { id: 52, departamentoId: 2, name: ' Liborina ' },
    { id: 53, departamentoId: 2, name: ' Olaya ' },
    { id: 54, departamentoId: 2, name: ' Peque ' },
    { id: 55, departamentoId: 2, name: ' Sabanalarga ' },
    { id: 56, departamentoId: 2, name: ' San Jerónimo ' },
    { id: 57, departamentoId: 2, name: ' Sopetrán ' },
    { id: 58, departamentoId: 2, name: ' Uramita ' },
    { id: 59, departamentoId: 2, name: ' Abejorral ' },
    { id: 60, departamentoId: 2, name: ' Alejandría ' },
    { id: 61, departamentoId: 2, name: ' Argelia ' },
    { id: 62, departamentoId: 2, name: ' El Carmen de Viboral ' },
    { id: 63, departamentoId: 2, name: ' Cocorná ' },
    { id: 64, departamentoId: 2, name: ' Concepción ' },
    { id: 65, departamentoId: 2, name: ' El Peñol ' },
    { id: 66, departamentoId: 2, name: ' El Retiro ' },
    { id: 67, departamentoId: 2, name: ' El Santuario ' },
    { id: 68, departamentoId: 2, name: ' Granada ' },
    { id: 69, departamentoId: 2, name: ' Guarne ' },
    { id: 70, departamentoId: 2, name: ' Guatapé ' },
    { id: 71, departamentoId: 2, name: ' La Ceja ' },
    { id: 72, departamentoId: 2, name: ' La Unión ' },
    { id: 73, departamentoId: 2, name: ' Marinilla ' },
    { id: 74, departamentoId: 2, name: ' Nariño ' },
    { id: 75, departamentoId: 2, name: ' Rionegro ' },
    { id: 76, departamentoId: 2, name: ' San Carlos ' },
    { id: 77, departamentoId: 2, name: ' San Francisco ' },
    { id: 78, departamentoId: 2, name: ' San Luis ' },
    { id: 79, departamentoId: 2, name: ' San Rafael ' },
    { id: 80, departamentoId: 2, name: ' San Vicente ' },
    { id: 81, departamentoId: 2, name: ' Sonsón ' },
    { id: 82, departamentoId: 2, name: ' Amagá ' },
    { id: 83, departamentoId: 2, name: ' Andes ' },
    { id: 84, departamentoId: 2, name: ' Angelópolis ' },
    { id: 85, departamentoId: 2, name: ' Betania ' },
    { id: 86, departamentoId: 2, name: ' Betulia ' },
    { id: 87, departamentoId: 2, name: ' Caramanta ' },
    { id: 88, departamentoId: 2, name: ' Ciudad Bolívar ' },
    { id: 89, departamentoId: 2, name: ' Concordia ' },
    { id: 90, departamentoId: 2, name: ' Fredonia ' },
    { id: 91, departamentoId: 2, name: ' Hispania ' },
    { id: 92, departamentoId: 2, name: ' Jardín ' },
    { id: 93, departamentoId: 2, name: ' Jericó ' },
    { id: 94, departamentoId: 2, name: ' La Pintada ' },
    { id: 95, departamentoId: 2, name: ' Montebello ' },
    { id: 96, departamentoId: 2, name: ' Pueblorrico ' },
    { id: 97, departamentoId: 2, name: ' Salgar ' },
    { id: 98, departamentoId: 2, name: ' Santa Bárbara ' },
    { id: 99, departamentoId: 2, name: ' Támesis ' },
    { id: 100, departamentoId: 2, name: ' Tarso ' },
    { id: 101, departamentoId: 2, name: ' Titiribí ' },
    { id: 102, departamentoId: 2, name: ' Urrao ' },
    { id: 103, departamentoId: 2, name: ' Valparaíso ' },
    { id: 104, departamentoId: 2, name: ' Venecia ' },
    { id: 105, departamentoId: 2, name: ' Apartadó ' },
    { id: 106, departamentoId: 2, name: ' Arboletes ' },
    { id: 107, departamentoId: 2, name: ' Carepa ' },
    { id: 108, departamentoId: 2, name: ' Chigorodó ' },
    { id: 109, departamentoId: 2, name: ' Murindó ' },
    { id: 110, departamentoId: 2, name: ' Mutatá ' },
    { id: 111, departamentoId: 2, name: ' Necoclí ' },
    { id: 112, departamentoId: 2, name: ' San Juan de Urabá ' },
    { id: 113, departamentoId: 2, name: ' San Pedro de Urabá ' },
    { id: 114, departamentoId: 2, name: ' Turbo ' },
    { id: 115, departamentoId: 2, name: ' Vigía del Fuerte ' },
    { id: 116, departamentoId: 2, name: ' Barbosa ' },
    { id: 117, departamentoId: 2, name: ' Bello ' },
    { id: 118, departamentoId: 2, name: ' Caldas ' },
    { id: 119, departamentoId: 2, name: ' Copacabana ' },
    { id: 120, departamentoId: 2, name: ' Envigado ' },
    { id: 121, departamentoId: 2, name: ' Girardota ' },
    { id: 122, departamentoId: 2, name: ' Itagüí ' },
    { id: 123, departamentoId: 2, name: ' La Estrella ' },
    { id: 124, departamentoId: 2, name: ' Medellín ' },
    { id: 125, departamentoId: 2, name: ' Sabaneta ' },


    { id: 1, departamentoId: 3, name: ' Arauca ' },
    { id: 2, departamentoId: 3, name: ' Arauquita ' },
    { id: 3, departamentoId: 3, name: ' Cravo Norte ' },
    { id: 4, departamentoId: 3, name: ' Fortul ' },
    { id: 5, departamentoId: 3, name: ' Puerto Rondón ' },
    { id: 6, departamentoId: 3, name: ' Saravena ' },
    { id: 7, departamentoId: 3, name: ' Tame ' },



    { id: 1, departamentoId: 4, name: ' Barranquilla ' },
    { id: 2, departamentoId: 4, name: ' Baranoa ' },
    { id: 3, departamentoId: 4, name: ' Campo de la Cruz ' },
    { id: 4, departamentoId: 4, name: ' Candelaria ' },
    { id: 5, departamentoId: 4, name: ' Galapa ' },
    { id: 6, departamentoId: 4, name: ' Juan de Acosta ' },
    { id: 7, departamentoId: 4, name: ' Luruaco ' },
    { id: 8, departamentoId: 4, name: ' Malambo ' },
    { id: 9, departamentoId: 4, name: ' Manatí ' },
    { id: 10, departamentoId: 4, name: ' Palmar de Varela ' },
    { id: 11, departamentoId: 4, name: ' Piojó ' },
    { id: 12, departamentoId: 4, name: ' Polonuevo ' },
    { id: 13, departamentoId: 4, name: ' Ponedera ' },
    { id: 14, departamentoId: 4, name: ' Puerto Colombia ' },
    { id: 15, departamentoId: 4, name: ' Repelón ' },
    { id: 16, departamentoId: 4, name: ' Sabanagrande ' },
    { id: 17, departamentoId: 4, name: ' Sabanalarga ' },
    { id: 18, departamentoId: 4, name: ' Santa Lucía ' },
    { id: 19, departamentoId: 4, name: ' Santo Tomás ' },
    { id: 20, departamentoId: 4, name: ' Soledad ' },
    { id: 21, departamentoId: 4, name: ' Suan ' },
    { id: 22, departamentoId: 4, name: ' Tubará ' },
    { id: 23, departamentoId: 4, name: ' Usiacurí ' },



    { id: 1, departamentoId: 5, name: 'Bogotá' },



    { id: 1, departamentoId: 6, name: ' Achí ' },
    { id: 2, departamentoId: 6, name: ' Altos del Rosario ' },
    { id: 3, departamentoId: 6, name: ' Arenal ' },
    { id: 4, departamentoId: 6, name: ' Arjona ' },
    { id: 5, departamentoId: 6, name: ' Arroyohondo ' },
    { id: 6, departamentoId: 6, name: ' Barranco de Loba ' },
    { id: 7, departamentoId: 6, name: ' Calamar ' },
    { id: 8, departamentoId: 6, name: ' Cantagallo ' },
    { id: 9, departamentoId: 6, name: ' El Carmen de Bolívar ' },
    { id: 10, departamentoId: 6, name: ' Cartagena de Indias ' },
    { id: 11, departamentoId: 6, name: ' Cicuco ' },
    { id: 12, departamentoId: 6, name: ' Clemencia ' },
    { id: 13, departamentoId: 6, name: ' Córdoba ' },
    { id: 14, departamentoId: 6, name: ' El Guamo ' },
    { id: 15, departamentoId: 6, name: ' El Peñón ' },
    { id: 16, departamentoId: 6, name: ' Hatillo de Loba ' },
    { id: 17, departamentoId: 6, name: ' Magangué ' },
    { id: 18, departamentoId: 6, name: ' Mahates ' },
    { id: 19, departamentoId: 6, name: ' Margarita ' },
    { id: 20, departamentoId: 6, name: ' María La Baja ' },
    { id: 21, departamentoId: 6, name: ' Montecristo ' },
    { id: 22, departamentoId: 6, name: ' Morales ' },
    { id: 23, departamentoId: 6, name: ' Norosí ' },
    { id: 24, departamentoId: 6, name: ' Pinillos ' },
    { id: 25, departamentoId: 6, name: ' Regidor ' },
    { id: 26, departamentoId: 6, name: ' Río Viejo ' },
    { id: 27, departamentoId: 6, name: ' San Cristóbal ' },
    { id: 28, departamentoId: 6, name: ' San Estanislao ' },
    { id: 29, departamentoId: 6, name: ' San Fernando ' },
    { id: 30, departamentoId: 6, name: ' San Jacinto ' },
    { id: 31, departamentoId: 6, name: ' San Jacinto del Cauca ' },
    { id: 32, departamentoId: 6, name: ' San Juan Nepomuceno ' },
    { id: 33, departamentoId: 6, name: ' San Martín de Loba ' },
    { id: 34, departamentoId: 6, name: ' San Pablo ' },
    { id: 35, departamentoId: 6, name: ' Santa Catalina ' },
    { id: 36, departamentoId: 6, name: ' Santa Cruz de Mompox ' },
    { id: 37, departamentoId: 6, name: ' Santa Rosa ' },
    { id: 38, departamentoId: 6, name: ' Santa Rosa del Sur ' },
    { id: 39, departamentoId: 6, name: ' Simití ' },
    { id: 40, departamentoId: 6, name: ' Soplaviento ' },
    { id: 41, departamentoId: 6, name: ' Talaigua Nuevo ' },
    { id: 42, departamentoId: 6, name: ' Tiquisio ' },
    { id: 43, departamentoId: 6, name: ' Turbaco ' },
    { id: 44, departamentoId: 6, name: ' Turbaná ' },
    { id: 45, departamentoId: 6, name: ' Villanueva ' },
    { id: 46, departamentoId: 6, name: ' Zambrano ' },



    { id: 1, departamentoId: 7, name: ' Chíquiza ' },
    { id: 2, departamentoId: 7, name: ' Chivatá ' },
    { id: 3, departamentoId: 7, name: ' Cómbita ' },
    { id: 4, departamentoId: 7, name: ' Cucaita ' },
    { id: 5, departamentoId: 7, name: ' Motavita ' },
    { id: 6, departamentoId: 7, name: ' Oicatá ' },
    { id: 7, departamentoId: 7, name: ' Samacá ' },
    { id: 8, departamentoId: 7, name: ' Siachoque ' },
    { id: 9, departamentoId: 7, name: ' Sora ' },
    { id: 10, departamentoId: 7, name: ' Soracá ' },
    { id: 11, departamentoId: 7, name: ' Sotaquirá ' },
    { id: 12, departamentoId: 7, name: ' Toca ' },
    { id: 13, departamentoId: 7, name: ' Tunja ' },
    { id: 14, departamentoId: 7, name: ' Tuta ' },
    { id: 15, departamentoId: 7, name: ' Ventaquemada ' },
    { id: 16, departamentoId: 7, name: ' Chiscas ' },
    { id: 17, departamentoId: 7, name: ' El Cocuy ' },
    { id: 18, departamentoId: 7, name: ' El Espino ' },
    { id: 19, departamentoId: 7, name: ' Guacamayas ' },
    { id: 20, departamentoId: 7, name: ' Güicán ' },
    { id: 21, departamentoId: 7, name: ' Panqueba ' },
    { id: 22, departamentoId: 7, name: ' Labranzagrande ' },
    { id: 23, departamentoId: 7, name: ' Pajarito ' },
    { id: 24, departamentoId: 7, name: ' Paya ' },
    { id: 25, departamentoId: 7, name: ' Pisba ' },
    { id: 26, departamentoId: 7, name: ' Berbeo ' },
    { id: 27, departamentoId: 7, name: ' Campohermoso ' },
    { id: 28, departamentoId: 7, name: ' Miraflores ' },
    { id: 29, departamentoId: 7, name: ' Páez ' },
    { id: 30, departamentoId: 7, name: ' San Eduardo ' },
    { id: 31, departamentoId: 7, name: ' Zetaquira ' },
    { id: 32, departamentoId: 7, name: ' Boyacá ' },
    { id: 33, departamentoId: 7, name: ' Ciénega ' },
    { id: 34, departamentoId: 7, name: ' Jenesano ' },
    { id: 35, departamentoId: 7, name: ' Nuevo Colón ' },
    { id: 36, departamentoId: 7, name: ' Ramiriquí ' },
    { id: 37, departamentoId: 7, name: ' Rondón ' },
    { id: 38, departamentoId: 7, name: ' Tibaná ' },
    { id: 39, departamentoId: 7, name: ' Turmequé ' },
    { id: 40, departamentoId: 7, name: ' Úmbita ' },
    { id: 41, departamentoId: 7, name: ' Viracachá ' },
    { id: 42, departamentoId: 7, name: ' Chinavita ' },
    { id: 43, departamentoId: 7, name: ' Garagoa ' },
    { id: 44, departamentoId: 7, name: ' Macanal ' },
    { id: 45, departamentoId: 7, name: ' Pachavita ' },
    { id: 46, departamentoId: 7, name: ' San Luis de Gaceno ' },
    { id: 47, departamentoId: 7, name: ' Santa María ' },
    { id: 48, departamentoId: 7, name: ' Boavita ' },
    { id: 49, departamentoId: 7, name: ' Covarachía ' },
    { id: 50, departamentoId: 7, name: ' La Uvita ' },
    { id: 51, departamentoId: 7, name: ' San Mateo ' },
    { id: 52, departamentoId: 7, name: ' Sativanorte ' },
    { id: 53, departamentoId: 7, name: ' Sativasur ' },
    { id: 54, departamentoId: 7, name: ' Soatá ' },
    { id: 55, departamentoId: 7, name: ' Susacón ' },
    { id: 56, departamentoId: 7, name: ' Tipacoque ' },
    { id: 57, departamentoId: 7, name: ' Briceño ' },
    { id: 58, departamentoId: 7, name: ' Buenavista ' },
    { id: 59, departamentoId: 7, name: ' Caldas ' },
    { id: 60, departamentoId: 7, name: ' Chiquinquirá ' },
    { id: 61, departamentoId: 7, name: ' Coper ' },
    { id: 62, departamentoId: 7, name: ' La Victoria ' },
    { id: 63, departamentoId: 7, name: ' Maripí ' },
    { id: 64, departamentoId: 7, name: ' Muzo ' },
    { id: 65, departamentoId: 7, name: ' Otanche ' },
    { id: 66, departamentoId: 7, name: ' Pauna ' },
    { id: 67, departamentoId: 7, name: ' Quípama ' },
    { id: 68, departamentoId: 7, name: ' Saboyá ' },
    { id: 69, departamentoId: 7, name: ' San Miguel de Sema ' },
    { id: 70, departamentoId: 7, name: ' San Pablo de Borbur ' },
    { id: 71, departamentoId: 7, name: ' Tununguá ' },
    { id: 72, departamentoId: 7, name: ' Almeida ' },
    { id: 73, departamentoId: 7, name: ' Chivor ' },
    { id: 74, departamentoId: 7, name: ' Guateque ' },
    { id: 75, departamentoId: 7, name: ' Guayatá ' },
    { id: 76, departamentoId: 7, name: ' La Capilla ' },
    { id: 77, departamentoId: 7, name: ' Somondoco ' },
    { id: 78, departamentoId: 7, name: ' Sutatenza ' },
    { id: 79, departamentoId: 7, name: ' Tenza ' },
    { id: 80, departamentoId: 7, name: ' Arcabuco ' },
    { id: 81, departamentoId: 7, name: ' Chitaraque ' },
    { id: 82, departamentoId: 7, name: ' Gachantivá ' },
    { id: 83, departamentoId: 7, name: ' Moniquirá ' },
    { id: 84, departamentoId: 7, name: ' Ráquira ' },
    { id: 85, departamentoId: 7, name: ' Sáchica ' },
    { id: 86, departamentoId: 7, name: ' San José de Pare ' },
    { id: 87, departamentoId: 7, name: ' Santa Sofía ' },
    { id: 88, departamentoId: 7, name: ' Santana ' },
    { id: 89, departamentoId: 7, name: ' Sutamarchán ' },
    { id: 90, departamentoId: 7, name: ' Tinjacá ' },
    { id: 91, departamentoId: 7, name: ' Togüí ' },
    { id: 92, departamentoId: 7, name: ' Villa de Leyva ' },
    { id: 93, departamentoId: 7, name: ' Aquitania ' },
    { id: 94, departamentoId: 7, name: ' Cuítiva ' },
    { id: 95, departamentoId: 7, name: ' Firavitoba ' },
    { id: 96, departamentoId: 7, name: ' Gámeza ' },
    { id: 97, departamentoId: 7, name: ' Iza ' },
    { id: 98, departamentoId: 7, name: ' Mongua ' },
    { id: 99, departamentoId: 7, name: ' Monguí ' },
    { id: 100, departamentoId: 7, name: ' Nobsa ' },
    { id: 101, departamentoId: 7, name: ' Pesca ' },
    { id: 102, departamentoId: 7, name: ' Sogamoso ' },
    { id: 103, departamentoId: 7, name: ' Tibasosa ' },
    { id: 104, departamentoId: 7, name: ' Tópaga ' },
    { id: 105, departamentoId: 7, name: ' Tota ' },
    { id: 106, departamentoId: 7, name: ' Belén ' },
    { id: 107, departamentoId: 7, name: ' Busbanzá ' },
    { id: 108, departamentoId: 7, name: ' Cerinza ' },
    { id: 109, departamentoId: 7, name: ' Corrales ' },
    { id: 110, departamentoId: 7, name: ' Duitama ' },
    { id: 111, departamentoId: 7, name: ' Floresta ' },
    { id: 112, departamentoId: 7, name: ' Paipa ' },
    { id: 113, departamentoId: 7, name: ' Santa Rosa de Viterbo ' },
    { id: 114, departamentoId: 7, name: ' Tutazá ' },
    { id: 115, departamentoId: 7, name: ' Betéitiva ' },
    { id: 116, departamentoId: 7, name: ' Chita ' },
    { id: 117, departamentoId: 7, name: ' Jericó ' },
    { id: 118, departamentoId: 7, name: ' Paz de Río ' },
    { id: 119, departamentoId: 7, name: ' Socha ' },
    { id: 120, departamentoId: 7, name: ' Socotá ' },
    { id: 121, departamentoId: 7, name: ' Tasco ' },
    { id: 122, departamentoId: 7, name: ' Cubará ' },
    { id: 123, departamentoId: 7, name: ' Puerto Boyacá ' },



    { id: 1, departamentoId: 8, name: ' Filadelfia ' },
    { id: 2, departamentoId: 8, name: ' La Merced ' },
    { id: 3, departamentoId: 8, name: ' Marmato ' },
    { id: 4, departamentoId: 8, name: ' Riosucio ' },
    { id: 5, departamentoId: 8, name: ' Supía ' },
    { id: 6, departamentoId: 8, name: ' Manzanares ' },
    { id: 7, departamentoId: 8, name: ' Marquetalia ' },
    { id: 8, departamentoId: 8, name: ' Marulanda ' },
    { id: 9, departamentoId: 8, name: ' Pensilvania ' },
    { id: 10, departamentoId: 8, name: ' Anserma ' },
    { id: 11, departamentoId: 8, name: ' Belalcázar ' },
    { id: 12, departamentoId: 8, name: ' Risaralda ' },
    { id: 13, departamentoId: 8, name: ' San José ' },
    { id: 14, departamentoId: 8, name: ' Viterbo ' },
    { id: 15, departamentoId: 8, name: ' Chinchiná ' },
    { id: 16, departamentoId: 8, name: ' Manizales ' },
    { id: 17, departamentoId: 8, name: ' Neira ' },
    { id: 18, departamentoId: 8, name: ' Palestina ' },
    { id: 19, departamentoId: 8, name: ' Villamaría ' },
    { id: 20, departamentoId: 8, name: ' La Dorada ' },
    { id: 21, departamentoId: 8, name: ' Norcasia ' },
    { id: 22, departamentoId: 8, name: ' Samaná ' },
    { id: 23, departamentoId: 8, name: ' Victoria ' },
    { id: 24, departamentoId: 8, name: ' Aguadas ' },
    { id: 25, departamentoId: 8, name: ' Aranzazu ' },
    { id: 26, departamentoId: 8, name: ' Pácora ' },
    { id: 27, departamentoId: 8, name: ' Salamina ' },



    { id: 1, departamentoId: 9, name: ' Albania ' },
    { id: 2, departamentoId: 9, name: ' Belén de los Andaquíes ' },
    { id: 3, departamentoId: 9, name: ' Cartagena del Chairá ' },
    { id: 4, departamentoId: 9, name: ' Curillo ' },
    { id: 5, departamentoId: 9, name: ' El Doncello ' },
    { id: 6, departamentoId: 9, name: ' El Paujil ' },
    { id: 7, departamentoId: 9, name: ' Florencia ' },
    { id: 8, departamentoId: 9, name: ' La Montañita ' },
    { id: 9, departamentoId: 9, name: ' Morelia ' },
    { id: 10, departamentoId: 9, name: ' Puerto Milán ' },
    { id: 11, departamentoId: 9, name: ' Puerto Rico ' },
    { id: 12, departamentoId: 9, name: ' San José del Fragua ' },
    { id: 13, departamentoId: 9, name: ' San Vicente del Caguán ' },
    { id: 14, departamentoId: 9, name: ' Solano ' },
    { id: 15, departamentoId: 9, name: ' Solita ' },
    { id: 16, departamentoId: 9, name: ' Valparaíso ' },



    { id: 1, departamentoId: 10, name: ' Aguazul ' },
    { id: 2, departamentoId: 10, name: ' Chámeza ' },
    { id: 3, departamentoId: 10, name: ' Hato Corozal ' },
    { id: 4, departamentoId: 10, name: ' La Salina ' },
    { id: 5, departamentoId: 10, name: ' Maní ' },
    { id: 6, departamentoId: 10, name: ' Monterrey ' },
    { id: 7, departamentoId: 10, name: ' Nunchía ' },
    { id: 8, departamentoId: 10, name: ' Orocué ' },
    { id: 9, departamentoId: 10, name: ' Paz de Ariporo ' },
    { id: 10, departamentoId: 10, name: ' Pore ' },
    { id: 11, departamentoId: 10, name: ' Recetor ' },
    { id: 12, departamentoId: 10, name: ' Sabanalarga ' },
    { id: 13, departamentoId: 10, name: ' Sácama ' },
    { id: 14, departamentoId: 10, name: ' San Luis de Palenque ' },
    { id: 15, departamentoId: 10, name: ' Támara ' },
    { id: 16, departamentoId: 10, name: ' Tauramena ' },
    { id: 17, departamentoId: 10, name: ' Trinidad ' },
    { id: 18, departamentoId: 10, name: ' Villanueva ' },
    { id: 19, departamentoId: 10, name: ' Yopal ' },



    { id: 1, departamentoId: 11, name: ' Buenos Aires ' },
    { id: 2, departamentoId: 11, name: ' Caloto ' },
    { id: 3, departamentoId: 11, name: ' Corinto ' },
    { id: 4, departamentoId: 11, name: ' Guachené ' },
    { id: 5, departamentoId: 11, name: ' Miranda ' },
    { id: 6, departamentoId: 11, name: ' Padilla ' },
    { id: 7, departamentoId: 11, name: ' Puerto Tejada ' },
    { id: 8, departamentoId: 11, name: ' Santander de Quilichao ' },
    { id: 9, departamentoId: 11, name: ' Suárez ' },
    { id: 10, departamentoId: 11, name: ' Villa Rica ' },
    { id: 11, departamentoId: 11, name: ' Cajibío ' },
    { id: 12, departamentoId: 11, name: ' El Tambo ' },
    { id: 13, departamentoId: 11, name: ' La Sierra ' },
    { id: 14, departamentoId: 11, name: ' Morales ' },
    { id: 15, departamentoId: 11, name: ' Piendamó ' },
    { id: 16, departamentoId: 11, name: ' Popayán ' },
    { id: 17, departamentoId: 11, name: ' Rosas ' },
    { id: 18, departamentoId: 11, name: ' Sotará ' },
    { id: 19, departamentoId: 11, name: ' Timbío ' },
    { id: 20, departamentoId: 11, name: ' Almaguer ' },
    { id: 21, departamentoId: 11, name: ' Argelia ' },
    { id: 22, departamentoId: 11, name: ' Balboa ' },
    { id: 23, departamentoId: 11, name: ' Bolívar ' },
    { id: 24, departamentoId: 11, name: ' Florencia ' },
    { id: 25, departamentoId: 11, name: ' La Vega ' },
    { id: 26, departamentoId: 11, name: ' Mercaderes ' },
    { id: 27, departamentoId: 11, name: ' Patía ' },
    { id: 28, departamentoId: 11, name: ' Piamonte ' },
    { id: 29, departamentoId: 11, name: ' San Sebastián ' },
    { id: 30, departamentoId: 11, name: ' Santa Rosa ' },
    { id: 31, departamentoId: 11, name: ' Sucre ' },
    { id: 32, departamentoId: 11, name: ' Guapi ' },
    { id: 33, departamentoId: 11, name: ' López de Micay ' },
    { id: 34, departamentoId: 11, name: ' Timbiquí ' },
    { id: 35, departamentoId: 11, name: ' Caldono ' },
    { id: 36, departamentoId: 11, name: ' Inzá ' },
    { id: 37, departamentoId: 11, name: ' Jambaló ' },
    { id: 38, departamentoId: 11, name: ' Páez ' },
    { id: 39, departamentoId: 11, name: ' Puracé - Coconuco ' },
    { id: 40, departamentoId: 11, name: ' Silvia ' },
    { id: 41, departamentoId: 11, name: ' Toribío ' },
    { id: 42, departamentoId: 11, name: ' Totoró ' },



    { id: 1, departamentoId: 12, name: ' Valledupar ' },
    { id: 2, departamentoId: 12, name: ' Aguachica ' },
    { id: 3, departamentoId: 12, name: ' Agustín Codazzi ' },
    { id: 4, departamentoId: 12, name: ' Bosconia ' },
    { id: 5, departamentoId: 12, name: ' Chimichagua ' },
    { id: 6, departamentoId: 12, name: ' El Copey ' },
    { id: 7, departamentoId: 12, name: ' San Alberto ' },
    { id: 8, departamentoId: 12, name: ' Curumaní ' },
    { id: 9, departamentoId: 12, name: ' El Paso ' },
    { id: 10, departamentoId: 12, name: ' La Paz ' },
    { id: 11, departamentoId: 12, name: ' Pueblo Bello ' },
    { id: 12, departamentoId: 12, name: ' La Jagua de Ibirico ' },
    { id: 13, departamentoId: 12, name: ' Chiriguaná ' },
    { id: 14, departamentoId: 12, name: ' Astrea ' },
    { id: 15, departamentoId: 12, name: ' San Martín ' },
    { id: 16, departamentoId: 12, name: ' Pelaya ' },
    { id: 17, departamentoId: 12, name: ' Pailitas ' },
    { id: 18, departamentoId: 12, name: ' Gamarra ' },
    { id: 19, departamentoId: 12, name: ' Manaure ' },
    { id: 20, departamentoId: 12, name: ' Río de Oro ' },
    { id: 21, departamentoId: 12, name: ' Tamalameque ' },
    { id: 22, departamentoId: 12, name: ' Becerril ' },
    { id: 23, departamentoId: 12, name: ' San Diego ' },
    { id: 24, departamentoId: 12, name: ' La Gloria ' },
    { id: 25, departamentoId: 12, name: ' González ' },


    { id: 1, departamentoId: 13, name: ' Acandí ' },
    { id: 2, departamentoId: 13, name: ' Alto Baudó ' },
    { id: 3, departamentoId: 13, name: ' Atrato ' },
    { id: 4, departamentoId: 13, name: ' Bagadó ' },
    { id: 5, departamentoId: 13, name: ' Bahía Solano ' },
    { id: 6, departamentoId: 13, name: ' Bajo Baudó ' },
    { id: 7, departamentoId: 13, name: ' Belén de Bajirá ' },
    { id: 8, departamentoId: 13, name: ' Bojayá ' },
    { id: 9, departamentoId: 13, name: ' Cértegui ' },
    { id: 10, departamentoId: 13, name: ' Condoto ' },
    { id: 11, departamentoId: 13, name: ' El Cantón de San Pablo ' },
    { id: 12, departamentoId: 13, name: ' El Carmen de Atrato ' },
    { id: 13, departamentoId: 13, name: ' El Carmen del Darién ' },
    { id: 14, departamentoId: 13, name: ' El Litoral de San Juan ' },
    { id: 15, departamentoId: 13, name: ' Istmina ' },
    { id: 16, departamentoId: 13, name: ' Juradó ' },
    { id: 17, departamentoId: 13, name: ' Lloró ' },
    { id: 18, departamentoId: 13, name: ' Medio Atrato ' },
    { id: 19, departamentoId: 13, name: ' Medio Baudó ' },
    { id: 20, departamentoId: 13, name: ' Medio San Juan ' },
    { id: 21, departamentoId: 13, name: ' Nóvita ' },
    { id: 22, departamentoId: 13, name: ' Nuquí ' },
    { id: 23, departamentoId: 13, name: ' Quibdó ' },
    { id: 24, departamentoId: 13, name: ' Río Iró ' },
    { id: 25, departamentoId: 13, name: ' Río Quito ' },
    { id: 26, departamentoId: 13, name: ' Riosucio ' },
    { id: 27, departamentoId: 13, name: ' San José del Palmar ' },
    { id: 28, departamentoId: 13, name: ' Sipí ' },
    { id: 29, departamentoId: 13, name: ' Tadó ' },
    { id: 30, departamentoId: 13, name: ' Unguía ' },
    { id: 31, departamentoId: 13, name: ' Unión Panamericana ' },


    { id: 1, departamentoId: 14, name: ' Ayapel ' },
    { id: 2, departamentoId: 14, name: ' Buenavista ' },
    { id: 3, departamentoId: 14, name: ' Canalete ' },
    { id: 4, departamentoId: 14, name: ' Cereté ' },
    { id: 5, departamentoId: 14, name: ' Chimá ' },
    { id: 6, departamentoId: 14, name: ' Chinú ' },
    { id: 7, departamentoId: 14, name: ' Ciénaga de Oro ' },
    { id: 8, departamentoId: 14, name: ' Cotorra ' },
    { id: 9, departamentoId: 14, name: ' La Apartada ' },
    { id: 10, departamentoId: 14, name: ' Los Córdobas ' },
    { id: 11, departamentoId: 14, name: ' Momil ' },
    { id: 12, departamentoId: 14, name: ' Montelíbano ' },
    { id: 13, departamentoId: 14, name: ' Montería ' },
    { id: 14, departamentoId: 14, name: ' Moñitos ' },
    { id: 15, departamentoId: 14, name: ' Planeta Rica ' },
    { id: 16, departamentoId: 14, name: ' Pueblo Nuevo ' },
    { id: 17, departamentoId: 14, name: ' Puerto Escondido ' },
    { id: 18, departamentoId: 14, name: ' Puerto Libertador ' },
    { id: 19, departamentoId: 14, name: ' Purísima ' },
    { id: 20, departamentoId: 14, name: ' Sahagún ' },
    { id: 21, departamentoId: 14, name: ' San Andrés de Sotavento ' },
    { id: 22, departamentoId: 14, name: ' San Antero ' },
    { id: 23, departamentoId: 14, name: ' San Bernardo del Viento ' },
    { id: 24, departamentoId: 14, name: ' San Carlos ' },
    { id: 25, departamentoId: 14, name: ' San José de Uré ' },
    { id: 26, departamentoId: 14, name: ' San Pelayo ' },
    { id: 27, departamentoId: 14, name: ' Santa Cruz de Lorica ' },
    { id: 28, departamentoId: 14, name: ' Tierralta ' },
    { id: 29, departamentoId: 14, name: ' Tuchín ' },
    { id: 30, departamentoId: 14, name: ' Valencia ' },


    { id: 1, departamentoId: 15, name: ' Chocontá ' },
    { id: 2, departamentoId: 15, name: ' Machetá ' },
    { id: 3, departamentoId: 15, name: ' Manta ' },
    { id: 4, departamentoId: 15, name: ' Sesquilé ' },
    { id: 5, departamentoId: 15, name: ' Suesca ' },
    { id: 6, departamentoId: 15, name: ' Tibirita ' },
    { id: 7, departamentoId: 15, name: ' Villapinzón ' },
    { id: 8, departamentoId: 15, name: ' Agua de Dios ' },
    { id: 9, departamentoId: 15, name: ' Girardot ' },
    { id: 10, departamentoId: 15, name: ' Guataquí ' },
    { id: 11, departamentoId: 15, name: ' Jerusalén ' },
    { id: 12, departamentoId: 15, name: ' Nariño ' },
    { id: 13, departamentoId: 15, name: ' Nilo ' },
    { id: 14, departamentoId: 15, name: ' Ricaurte ' },
    { id: 15, departamentoId: 15, name: ' Tocaima ' },
    { id: 16, departamentoId: 15, name: ' Caparrapí ' },
    { id: 17, departamentoId: 15, name: ' Guaduas ' },
    { id: 18, departamentoId: 15, name: ' Puerto Salgar ' },
    { id: 19, departamentoId: 15, name: ' Albán ' },
    { id: 20, departamentoId: 15, name: ' La Peña ' },
    { id: 21, departamentoId: 15, name: ' La Vega ' },
    { id: 22, departamentoId: 15, name: ' Nimaima ' },
    { id: 23, departamentoId: 15, name: ' Nocaima ' },
    { id: 24, departamentoId: 15, name: ' Quebradanegra ' },
    { id: 25, departamentoId: 15, name: ' San Francisco ' },
    { id: 26, departamentoId: 15, name: ' Sasaima ' },
    { id: 27, departamentoId: 15, name: ' Supatá ' },
    { id: 28, departamentoId: 15, name: ' Útica ' },
    { id: 29, departamentoId: 15, name: ' Vergara ' },
    { id: 30, departamentoId: 15, name: ' Villeta ' },
    { id: 31, departamentoId: 15, name: ' Gachalá ' },
    { id: 32, departamentoId: 15, name: ' Gachetá ' },
    { id: 33, departamentoId: 15, name: ' Gama ' },
    { id: 34, departamentoId: 15, name: ' Guasca ' },
    { id: 35, departamentoId: 15, name: ' Guatavita ' },
    { id: 36, departamentoId: 15, name: ' Junín ' },
    { id: 37, departamentoId: 15, name: ' La Calera ' },
    { id: 38, departamentoId: 15, name: ' Ubalá ' },
    { id: 39, departamentoId: 15, name: ' Beltrán ' },
    { id: 40, departamentoId: 15, name: ' Bituima ' },
    { id: 41, departamentoId: 15, name: ' Chaguaní ' },
    { id: 42, departamentoId: 15, name: ' Guayabal de Síquima ' },
    { id: 43, departamentoId: 15, name: ' Pulí ' },
    { id: 44, departamentoId: 15, name: ' San Juan de Rioseco ' },
    { id: 45, departamentoId: 15, name: ' Vianí ' },
    { id: 46, departamentoId: 15, name: ' Medina ' },
    { id: 47, departamentoId: 15, name: ' Paratebueno ' },
    { id: 48, departamentoId: 15, name: ' Cáqueza ' },
    { id: 49, departamentoId: 15, name: ' Chipaque ' },
    { id: 50, departamentoId: 15, name: ' Choachí ' },
    { id: 51, departamentoId: 15, name: ' Fómeque ' },
    { id: 52, departamentoId: 15, name: ' Fosca ' },
    { id: 53, departamentoId: 15, name: ' Guayabetal ' },
    { id: 54, departamentoId: 15, name: ' Gutiérrez ' },
    { id: 55, departamentoId: 15, name: ' Quetame ' },
    { id: 56, departamentoId: 15, name: ' Ubaque ' },
    { id: 57, departamentoId: 15, name: ' Une ' },
    { id: 58, departamentoId: 15, name: ' El Peñón ' },
    { id: 59, departamentoId: 15, name: ' La Palma ' },
    { id: 60, departamentoId: 15, name: ' Pacho ' },
    { id: 61, departamentoId: 15, name: ' Paime ' },
    { id: 62, departamentoId: 15, name: ' San Cayetano ' },
    { id: 63, departamentoId: 15, name: ' Topaipí ' },
    { id: 64, departamentoId: 15, name: ' Villagómez ' },
    { id: 65, departamentoId: 15, name: ' Yacopí ' },
    { id: 66, departamentoId: 15, name: ' Cajicá ' },
    { id: 67, departamentoId: 15, name: ' Chía ' },
    { id: 68, departamentoId: 15, name: ' Cogua ' },
    { id: 69, departamentoId: 15, name: ' Cota ' },
    { id: 70, departamentoId: 15, name: ' Gachancipá ' },
    { id: 71, departamentoId: 15, name: ' Nemocón ' },
    { id: 72, departamentoId: 15, name: ' Sopó ' },
    { id: 73, departamentoId: 15, name: ' Tabio ' },
    { id: 74, departamentoId: 15, name: ' Tenjo ' },
    { id: 75, departamentoId: 15, name: ' Tocancipá ' },
    { id: 76, departamentoId: 15, name: ' Zipaquirá ' },
    { id: 77, departamentoId: 15, name: ' Bojacá ' },
    { id: 78, departamentoId: 15, name: ' El Rosal ' },
    { id: 79, departamentoId: 15, name: ' Facatativá ' },
    { id: 80, departamentoId: 15, name: ' Funza ' },
    { id: 81, departamentoId: 15, name: ' Madrid ' },
    { id: 82, departamentoId: 15, name: ' Mosquera ' },
    { id: 83, departamentoId: 15, name: ' Subachoque ' },
    { id: 84, departamentoId: 15, name: ' Zipacón ' },
    { id: 85, departamentoId: 15, name: ' Sibaté ' },
    { id: 86, departamentoId: 15, name: ' Soacha ' },
    { id: 87, departamentoId: 15, name: ' Arbeláez ' },
    { id: 88, departamentoId: 15, name: ' Cabrera ' },
    { id: 89, departamentoId: 15, name: ' Fusagasugá ' },
    { id: 90, departamentoId: 15, name: ' Granada ' },
    { id: 91, departamentoId: 15, name: ' Pandi ' },
    { id: 92, departamentoId: 15, name: ' Pasca ' },
    { id: 93, departamentoId: 15, name: ' San Bernardo ' },
    { id: 94, departamentoId: 15, name: ' Silvania ' },
    { id: 95, departamentoId: 15, name: ' Tibacuy ' },
    { id: 96, departamentoId: 15, name: ' Venecia ' },
    { id: 97, departamentoId: 15, name: ' Anapoima ' },
    { id: 98, departamentoId: 15, name: ' Anolaima ' },
    { id: 99, departamentoId: 15, name: ' Apulo ' },
    { id: 100, departamentoId: 15, name: ' Cachipay ' },
    { id: 101, departamentoId: 15, name: ' El Colegio ' },
    { id: 102, departamentoId: 15, name: ' La Mesa ' },
    { id: 103, departamentoId: 15, name: ' Quipile ' },
    { id: 104, departamentoId: 15, name: ' San Antonio del Tequendama ' },
    { id: 105, departamentoId: 15, name: ' Tena ' },
    { id: 106, departamentoId: 15, name: ' Viotá ' },
    { id: 107, departamentoId: 15, name: ' Carmen de Carupa ' },
    { id: 108, departamentoId: 15, name: ' Cucunubá ' },
    { id: 109, departamentoId: 15, name: ' Fúquene ' },
    { id: 110, departamentoId: 15, name: ' Guachetá ' },
    { id: 111, departamentoId: 15, name: ' Lenguazaque ' },
    { id: 112, departamentoId: 15, name: ' Simijaca ' },
    { id: 113, departamentoId: 15, name: ' Susa ' },
    { id: 114, departamentoId: 15, name: ' Sutatausa ' },
    { id: 115, departamentoId: 15, name: ' Tausa ' },
    { id: 116, departamentoId: 15, name: ' Ubaté ' },


    { id: 1, departamentoId: 16, name: ' Barrancominas ' },
    { id: 2, departamentoId: 16, name: ' Cacahual ' },
    { id: 3, departamentoId: 16, name: ' Inírida ' },
    { id: 4, departamentoId: 16, name: ' La Guadalupe ' },
    { id: 5, departamentoId: 16, name: ' Morichal Nuevo ' },
    { id: 6, departamentoId: 16, name: ' Pana Pana ' },
    { id: 7, departamentoId: 16, name: ' Puerto Colombia ' },
    { id: 8, departamentoId: 16, name: ' San Felipe ' },


    { id: 1, departamentoId: 17, name: ' Calamar ' },
    { id: 2, departamentoId: 17, name: ' El Retorno ' },
    { id: 3, departamentoId: 17, name: ' Miraflores ' },
    { id: 4, departamentoId: 17, name: ' San José del Guaviare ' },


    { id: 1, departamentoId: 18, name: ' Aipe ' },
    { id: 2, departamentoId: 18, name: ' Algeciras ' },
    { id: 3, departamentoId: 18, name: ' Baraya ' },
    { id: 4, departamentoId: 18, name: ' Campoalegre ' },
    { id: 5, departamentoId: 18, name: ' Colombia ' },
    { id: 6, departamentoId: 18, name: ' Hobo ' },
    { id: 7, departamentoId: 18, name: ' Íquira ' },
    { id: 8, departamentoId: 18, name: ' Neiva ' },
    { id: 9, departamentoId: 18, name: ' Palermo ' },
    { id: 10, departamentoId: 18, name: ' Rivera ' },
    { id: 11, departamentoId: 18, name: ' Santa María ' },
    { id: 12, departamentoId: 18, name: ' Tello ' },
    { id: 13, departamentoId: 18, name: ' Teruel ' },
    { id: 14, departamentoId: 18, name: ' Villavieja ' },
    { id: 15, departamentoId: 18, name: ' Yaguará ' },
    { id: 16, departamentoId: 18, name: ' Agrado ' },
    { id: 17, departamentoId: 18, name: ' Altamira ' },
    { id: 18, departamentoId: 18, name: ' Garzón ' },
    { id: 19, departamentoId: 18, name: ' Gigante ' },
    { id: 20, departamentoId: 18, name: ' Guadalupe ' },
    { id: 21, departamentoId: 18, name: ' Pital ' },
    { id: 22, departamentoId: 18, name: ' Suaza ' },
    { id: 23, departamentoId: 18, name: ' Tarqui ' },
    { id: 24, departamentoId: 18, name: ' La Argentina ' },
    { id: 25, departamentoId: 18, name: ' La Plata ' },
    { id: 26, departamentoId: 18, name: ' Nátaga ' },
    { id: 27, departamentoId: 18, name: ' Paicol ' },
    { id: 28, departamentoId: 18, name: ' Tesalia ' },
    { id: 29, departamentoId: 18, name: ' Acevedo ' },
    { id: 30, departamentoId: 18, name: ' Elías ' },
    { id: 31, departamentoId: 18, name: ' Isnos ' },
    { id: 32, departamentoId: 18, name: ' Oporapa ' },
    { id: 33, departamentoId: 18, name: ' Palestina ' },
    { id: 34, departamentoId: 18, name: ' Pitalito ' },
    { id: 35, departamentoId: 18, name: ' Saladoblanco ' },
    { id: 36, departamentoId: 18, name: ' San Agustín ' },
    { id: 37, departamentoId: 18, name: ' Timaná ' },


    { id: 1, departamentoId: 19, name: ' Albania ' },
    { id: 2, departamentoId: 19, name: ' Barrancas ' },
    { id: 3, departamentoId: 19, name: ' Dibulla ' },
    { id: 4, departamentoId: 19, name: ' Distracción ' },
    { id: 5, departamentoId: 19, name: ' El Molino ' },
    { id: 6, departamentoId: 19, name: ' Fonseca ' },
    { id: 7, departamentoId: 19, name: ' Hatonuevo ' },
    { id: 8, departamentoId: 19, name: ' La Jagua del Pilar ' },
    { id: 9, departamentoId: 19, name: ' Maicao ' },
    { id: 10, departamentoId: 19, name: ' Manaure ' },
    { id: 11, departamentoId: 19, name: ' Riohacha ' },
    { id: 12, departamentoId: 19, name: ' San Juan del Cesar ' },
    { id: 13, departamentoId: 19, name: ' Uribia ' },
    { id: 14, departamentoId: 19, name: ' Urumita ' },
    { id: 15, departamentoId: 19, name: ' Villanueva ' },


    { id: 1, departamentoId: 20, name: ' Algarrobo ' },
    { id: 2, departamentoId: 20, name: ' Aracataca ' },
    { id: 3, departamentoId: 20, name: ' Ariguaní ' },
    { id: 4, departamentoId: 20, name: ' Cerro de San Antonio ' },
    { id: 5, departamentoId: 20, name: ' Chibolo ' },
    { id: 6, departamentoId: 20, name: ' Ciénaga ' },
    { id: 7, departamentoId: 20, name: ' Concordia ' },
    { id: 8, departamentoId: 20, name: ' El Banco ' },
    { id: 9, departamentoId: 20, name: ' El Piñón ' },
    { id: 10, departamentoId: 20, name: ' El Retén ' },
    { id: 11, departamentoId: 20, name: ' Fundación ' },
    { id: 12, departamentoId: 20, name: ' Guamal ' },
    { id: 13, departamentoId: 20, name: ' Nueva Granada ' },
    { id: 14, departamentoId: 20, name: ' Pedraza ' },
    { id: 15, departamentoId: 20, name: ' Pijiño del Carmen ' },
    { id: 16, departamentoId: 20, name: ' Pivijay ' },
    { id: 17, departamentoId: 20, name: ' Plato ' },
    { id: 18, departamentoId: 20, name: ' Pueblo Viejo ' },
    { id: 19, departamentoId: 20, name: ' Remolino ' },
    { id: 20, departamentoId: 20, name: ' Sabanas de San Ángel ' },
    { id: 21, departamentoId: 20, name: ' Salamina ' },
    { id: 22, departamentoId: 20, name: ' San Sebastián de Buenavista ' },
    { id: 23, departamentoId: 20, name: ' Santa Ana ' },
    { id: 24, departamentoId: 20, name: ' Santa Bárbara de Pinto ' },
    { id: 25, departamentoId: 20, name: ' Santa Marta ' },
    { id: 26, departamentoId: 20, name: ' San Zenón ' },
    { id: 27, departamentoId: 20, name: ' Sitionuevo ' },
    { id: 28, departamentoId: 20, name: ' Tenerife ' },
    { id: 29, departamentoId: 20, name: ' Zapayán ' },
    { id: 30, departamentoId: 20, name: ' Zona Bananera ' },


    { id: 1, departamentoId: 21, name: ' Acacías ' },
    { id: 2, departamentoId: 21, name: ' Barranca de Upía ' },
    { id: 3, departamentoId: 21, name: ' Cabuyaro ' },
    { id: 4, departamentoId: 21, name: ' Castilla La Nueva ' },
    { id: 5, departamentoId: 21, name: ' Cubarral ' },
    { id: 6, departamentoId: 21, name: ' Cumaral ' },
    { id: 7, departamentoId: 21, name: ' El Calvario ' },
    { id: 8, departamentoId: 21, name: ' El Castillo ' },
    { id: 9, departamentoId: 21, name: ' El Dorado ' },
    { id: 10, departamentoId: 21, name: ' Fuente de Oro ' },
    { id: 11, departamentoId: 21, name: ' Granada ' },
    { id: 12, departamentoId: 21, name: ' Guamal ' },
    { id: 13, departamentoId: 21, name: ' La Macarena ' },
    { id: 14, departamentoId: 21, name: ' Uribe ' },
    { id: 15, departamentoId: 21, name: ' Lejanías ' },
    { id: 16, departamentoId: 21, name: ' Mapiripán ' },
    { id: 17, departamentoId: 21, name: ' Mesetas ' },
    { id: 18, departamentoId: 21, name: ' Puerto Concordia ' },
    { id: 19, departamentoId: 21, name: ' Puerto Gaitán ' },
    { id: 20, departamentoId: 21, name: ' Puerto Lleras ' },
    { id: 21, departamentoId: 21, name: ' Puerto López ' },
    { id: 22, departamentoId: 21, name: ' Puerto Rico ' },
    { id: 23, departamentoId: 21, name: ' Restrepo ' },
    { id: 24, departamentoId: 21, name: ' San Carlos de Guaroa ' },
    { id: 25, departamentoId: 21, name: ' San Juan de Arama ' },
    { id: 26, departamentoId: 21, name: ' San Juanito ' },
    { id: 27, departamentoId: 21, name: ' San Martín ' },
    { id: 28, departamentoId: 21, name: ' Villavicencio ' },
    { id: 29, departamentoId: 21, name: ' Vista Hermosa ' },


    { id: 1, departamentoId: 22, name: ' Barbacoas ' },
    { id: 2, departamentoId: 22, name: ' El Charco ' },
    { id: 3, departamentoId: 22, name: ' Francisco Pizarro ' },
    { id: 4, departamentoId: 22, name: ' La Tola ' },
    { id: 5, departamentoId: 22, name: ' Magüí Payán ' },
    { id: 6, departamentoId: 22, name: ' Mosquera ' },
    { id: 7, departamentoId: 22, name: ' Olaya Herrera ' },
    { id: 8, departamentoId: 22, name: ' Roberto Payán ' },
    { id: 9, departamentoId: 22, name: ' Santa Bárbara ' },
    { id: 10, departamentoId: 22, name: ' Tumaco ' },
    { id: 11, departamentoId: 22, name: ' Aldana ' },
    { id: 12, departamentoId: 22, name: ' Contadero ' },
    { id: 13, departamentoId: 22, name: ' Córdoba ' },
    { id: 14, departamentoId: 22, name: ' Cuaspud ' },
    { id: 15, departamentoId: 22, name: ' Cumbal ' },
    { id: 16, departamentoId: 22, name: ' Funes ' },
    { id: 17, departamentoId: 22, name: ' Guachucal ' },
    { id: 18, departamentoId: 22, name: ' Gualmatán ' },
    { id: 19, departamentoId: 22, name: ' Iles ' },
    { id: 20, departamentoId: 22, name: ' Ipiales ' },
    { id: 21, departamentoId: 22, name: ' Potosí ' },
    { id: 22, departamentoId: 22, name: ' Puerres ' },
    { id: 23, departamentoId: 22, name: ' Pupiales ' },
    { id: 24, departamentoId: 22, name: ' Albán ' },
    { id: 25, departamentoId: 22, name: ' Arboleda ' },
    { id: 26, departamentoId: 22, name: ' Belén ' },
    { id: 27, departamentoId: 22, name: ' Colón ' },
    { id: 28, departamentoId: 22, name: ' El Rosario ' },
    { id: 29, departamentoId: 22, name: ' El Tablón de Gómez ' },
    { id: 30, departamentoId: 22, name: ' La Cruz ' },
    { id: 31, departamentoId: 22, name: ' La Unión ' },
    { id: 32, departamentoId: 22, name: ' Leiva ' },
    { id: 33, departamentoId: 22, name: ' Policarpa ' },
    { id: 34, departamentoId: 22, name: ' San Bernardo ' },
    { id: 35, departamentoId: 22, name: ' San Lorenzo ' },
    { id: 36, departamentoId: 22, name: ' San Pablo ' },
    { id: 37, departamentoId: 22, name: ' San Pedro de Cartago ' },
    { id: 38, departamentoId: 22, name: ' Taminango ' },
    { id: 39, departamentoId: 22, name: ' Buesaco ' },
    { id: 40, departamentoId: 22, name: ' Chachagüí ' },
    { id: 41, departamentoId: 22, name: ' Consacá ' },
    { id: 42, departamentoId: 22, name: ' El Peñol ' },
    { id: 43, departamentoId: 22, name: ' El Tambo ' },
    { id: 44, departamentoId: 22, name: ' La Florida ' },
    { id: 45, departamentoId: 22, name: ' Nariño ' },
    { id: 46, departamentoId: 22, name: ' Pasto ' },
    { id: 47, departamentoId: 22, name: ' Sandoná ' },
    { id: 48, departamentoId: 22, name: ' Tangua ' },
    { id: 49, departamentoId: 22, name: ' Yacuanquer ' },
    { id: 50, departamentoId: 22, name: ' Ancuya ' },
    { id: 51, departamentoId: 22, name: ' Cumbitara ' },
    { id: 52, departamentoId: 22, name: ' Guaitarilla ' },
    { id: 53, departamentoId: 22, name: ' Imués ' },
    { id: 54, departamentoId: 22, name: ' La Llanada ' },
    { id: 55, departamentoId: 22, name: ' Linares ' },
    { id: 56, departamentoId: 22, name: ' Los Andes ' },
    { id: 57, departamentoId: 22, name: ' Mallama ' },
    { id: 58, departamentoId: 22, name: ' Ospina ' },
    { id: 59, departamentoId: 22, name: ' Providencia ' },
    { id: 60, departamentoId: 22, name: ' Ricaurte ' },
    { id: 61, departamentoId: 22, name: ' Samaniego ' },
    { id: 62, departamentoId: 22, name: ' Santacruz ' },
    { id: 63, departamentoId: 22, name: ' Sapuyes ' },
    { id: 64, departamentoId: 22, name: ' Túquerres ' },


    { id: 1, departamentoId: 23, name: ' Arboledas ' },
    { id: 2, departamentoId: 23, name: ' Cucutilla ' },
    { id: 3, departamentoId: 23, name: ' Gramalote ' },
    { id: 4, departamentoId: 23, name: ' Lourdes ' },
    { id: 5, departamentoId: 23, name: ' Salazar de Las Palmas ' },
    { id: 6, departamentoId: 23, name: ' Santiago ' },
    { id: 7, departamentoId: 23, name: ' Villa Caro ' },
    { id: 8, departamentoId: 23, name: ' Cúcuta ' },
    { id: 9, departamentoId: 23, name: ' El Zulia ' },
    { id: 10, departamentoId: 23, name: ' Los Patios ' },
    { id: 11, departamentoId: 23, name: ' Puerto Santander ' },
    { id: 12, departamentoId: 23, name: ' San Cayetano ' },
    { id: 13, departamentoId: 23, name: ' Villa del Rosario ' },
    { id: 14, departamentoId: 23, name: ' Bucarasica ' },
    { id: 15, departamentoId: 23, name: ' El Tarra ' },
    { id: 16, departamentoId: 23, name: ' Sardinata ' },
    { id: 17, departamentoId: 23, name: ' Tibú ' },
    { id: 18, departamentoId: 23, name: ' Ábrego ' },
    { id: 19, departamentoId: 23, name: ' Cáchira ' },
    { id: 20, departamentoId: 23, name: ' Convención ' },
    { id: 21, departamentoId: 23, name: ' El Carmen ' },
    { id: 22, departamentoId: 23, name: ' Hacarí ' },
    { id: 23, departamentoId: 23, name: ' La Esperanza ' },
    { id: 24, departamentoId: 23, name: ' La Playa de Belén ' },
    { id: 25, departamentoId: 23, name: ' Ocaña ' },
    { id: 26, departamentoId: 23, name: ' San Calixto ' },
    { id: 27, departamentoId: 23, name: ' Teorama ' },
    { id: 28, departamentoId: 23, name: ' Cácota ' },
    { id: 29, departamentoId: 23, name: ' Chitagá ' },
    { id: 30, departamentoId: 23, name: ' Mutiscua ' },
    { id: 31, departamentoId: 23, name: ' Pamplona ' },
    { id: 32, departamentoId: 23, name: ' Pamplonita ' },
    { id: 33, departamentoId: 23, name: ' Santo Domingo de Silos ' },
    { id: 34, departamentoId: 23, name: ' Bochalema ' },
    { id: 35, departamentoId: 23, name: ' Chinácota ' },
    { id: 36, departamentoId: 23, name: ' Durania ' },
    { id: 37, departamentoId: 23, name: ' Herrán ' },
    { id: 38, departamentoId: 23, name: ' Labateca ' },
    { id: 39, departamentoId: 23, name: ' Ragonvalia ' },
    { id: 40, departamentoId: 23, name: ' Toledo ' },

    { id: 1, departamentoId: 24, name: ' Colón ' },
    { id: 2, departamentoId: 24, name: ' Mocoa ' },
    { id: 3, departamentoId: 24, name: ' Orito ' },
    { id: 4, departamentoId: 24, name: ' Puerto Asís ' },
    { id: 5, departamentoId: 24, name: ' Puerto Caicedo ' },
    { id: 6, departamentoId: 24, name: ' Puerto Guzmán ' },
    { id: 7, departamentoId: 24, name: ' Puerto Leguízamo ' },
    { id: 8, departamentoId: 24, name: ' San Francisco ' },
    { id: 9, departamentoId: 24, name: ' San Miguel ' },
    { id: 10, departamentoId: 24, name: ' Santiago ' },
    { id: 11, departamentoId: 24, name: ' Sibundoy ' },
    { id: 12, departamentoId: 24, name: ' Valle del Guamuez ' },
    { id: 13, departamentoId: 24, name: ' Villagarzón ' },

    { id: 1, departamentoId: 25, name: ' Armenia ' },
    { id: 2, departamentoId: 25, name: ' Buenavista ' },
    { id: 3, departamentoId: 25, name: ' Calarcá ' },
    { id: 4, departamentoId: 25, name: ' Circasia ' },
    { id: 5, departamentoId: 25, name: ' Córdoba ' },
    { id: 6, departamentoId: 25, name: ' Filandia ' },
    { id: 7, departamentoId: 25, name: ' Génova ' },
    { id: 8, departamentoId: 25, name: ' La Tebaida ' },
    { id: 9, departamentoId: 25, name: ' Montenegro ' },
    { id: 10, departamentoId: 25, name: ' Pijao ' },
    { id: 11, departamentoId: 25, name: ' Quimbaya ' },
    { id: 12, departamentoId: 25, name: ' Salento ' },


    { id: 1, departamentoId: 26, name: ' Apía ' },
    { id: 2, departamentoId: 26, name: ' Balboa ' },
    { id: 3, departamentoId: 26, name: ' Belén de Umbría ' },
    { id: 4, departamentoId: 26, name: ' Dosquebradas ' },
    { id: 5, departamentoId: 26, name: ' Guática ' },
    { id: 6, departamentoId: 26, name: ' La Celia ' },
    { id: 7, departamentoId: 26, name: ' La Virginia ' },
    { id: 8, departamentoId: 26, name: ' Marsella ' },
    { id: 9, departamentoId: 26, name: ' Mistrató ' },
    { id: 10, departamentoId: 26, name: ' Pereira ' },
    { id: 11, departamentoId: 26, name: ' Pueblo Rico ' },
    { id: 12, departamentoId: 26, name: ' Quinchía ' },
    { id: 13, departamentoId: 26, name: ' Santa Rosa de Cabal ' },
    { id: 14, departamentoId: 26, name: ' Santuario ' },


    { id: 1, departamentoId: 27, name: ' San Andrés ' },
    { id: 2, departamentoId: 27, name: ' Providencia ' },
    { id: 3, departamentoId: 27, name: ' Santa Catalina ' },

    { id: 1, departamentoId: 28, name: ' Aguada ' },
    { id: 2, departamentoId: 28, name: ' Albania ' },
    { id: 3, departamentoId: 28, name: ' Aratoca ' },
    { id: 4, departamentoId: 28, name: ' Barbosa ' },
    { id: 5, departamentoId: 28, name: ' Barichara ' },
    { id: 6, departamentoId: 28, name: ' Barrancabermeja ' },
    { id: 7, departamentoId: 28, name: ' Betulia ' },
    { id: 8, departamentoId: 28, name: ' Bolívar ' },
    { id: 9, departamentoId: 28, name: ' Bucaramanga ' },
    { id: 10, departamentoId: 28, name: ' Cabrera ' },
    { id: 11, departamentoId: 28, name: ' California ' },
    { id: 12, departamentoId: 28, name: ' Capitanejo ' },
    { id: 13, departamentoId: 28, name: ' Carcasí ' },
    { id: 14, departamentoId: 28, name: ' Cepitá ' },
    { id: 15, departamentoId: 28, name: ' Cerrito ' },
    { id: 16, departamentoId: 28, name: ' Charalá ' },
    { id: 17, departamentoId: 28, name: ' Charta ' },
    { id: 18, departamentoId: 28, name: ' Chima ' },
    { id: 19, departamentoId: 28, name: ' Chipatá ' },
    { id: 20, departamentoId: 28, name: ' Cimitarra ' },
    { id: 21, departamentoId: 28, name: ' Concepción ' },
    { id: 22, departamentoId: 28, name: ' Confines ' },
    { id: 23, departamentoId: 28, name: ' Contratación ' },
    { id: 24, departamentoId: 28, name: ' Coromoro ' },
    { id: 25, departamentoId: 28, name: ' Curití ' },
    { id: 26, departamentoId: 28, name: ' El Carmen de Chucurí ' },
    { id: 27, departamentoId: 28, name: ' El Guacamayo ' },
    { id: 28, departamentoId: 28, name: ' El Peñón ' },
    { id: 29, departamentoId: 28, name: ' El Playón ' },
    { id: 30, departamentoId: 28, name: ' Encino ' },
    { id: 31, departamentoId: 28, name: ' Enciso ' },
    { id: 32, departamentoId: 28, name: ' Florián ' },
    { id: 33, departamentoId: 28, name: ' Floridablanca ' },
    { id: 34, departamentoId: 28, name: ' Galán ' },
    { id: 35, departamentoId: 28, name: ' Gámbita ' },
    { id: 36, departamentoId: 28, name: ' Girón ' },
    { id: 37, departamentoId: 28, name: ' Guaca ' },
    { id: 38, departamentoId: 28, name: ' Guadalupe ' },
    { id: 39, departamentoId: 28, name: ' Guapotá ' },
    { id: 40, departamentoId: 28, name: ' Guavatá ' },
    { id: 41, departamentoId: 28, name: ' Güepsa ' },
    { id: 42, departamentoId: 28, name: ' Hato ' },
    { id: 43, departamentoId: 28, name: ' Jesús María ' },
    { id: 44, departamentoId: 28, name: ' Jordán ' },
    { id: 45, departamentoId: 28, name: ' La Belleza ' },
    { id: 46, departamentoId: 28, name: ' La Paz ' },
    { id: 47, departamentoId: 28, name: ' Landázuri ' },
    { id: 48, departamentoId: 28, name: ' Lebrija ' },
    { id: 49, departamentoId: 28, name: ' Los Santos ' },
    { id: 50, departamentoId: 28, name: ' Macaravita ' },
    { id: 51, departamentoId: 28, name: ' Málaga ' },
    { id: 52, departamentoId: 28, name: ' Matanza ' },
    { id: 53, departamentoId: 28, name: ' Mogotes ' },
    { id: 54, departamentoId: 28, name: ' Molagavita ' },
    { id: 55, departamentoId: 28, name: ' Ocamonte ' },
    { id: 56, departamentoId: 28, name: ' Oiba ' },
    { id: 57, departamentoId: 28, name: ' Onzaga ' },
    { id: 58, departamentoId: 28, name: ' Palmar ' },
    { id: 59, departamentoId: 28, name: ' Palmas del Socorro ' },
    { id: 60, departamentoId: 28, name: ' Páramo ' },
    { id: 61, departamentoId: 28, name: ' Piedecuesta ' },
    { id: 62, departamentoId: 28, name: ' Pinchote ' },
    { id: 63, departamentoId: 28, name: ' Puente Nacional ' },
    { id: 64, departamentoId: 28, name: ' Puerto Parra ' },
    { id: 65, departamentoId: 28, name: ' Puerto Wilches ' },
    { id: 66, departamentoId: 28, name: ' Rionegro ' },
    { id: 67, departamentoId: 28, name: ' Sabana de Torres ' },
    { id: 68, departamentoId: 28, name: ' San Andrés ' },
    { id: 69, departamentoId: 28, name: ' San Benito ' },
    { id: 70, departamentoId: 28, name: ' San Gil ' },
    { id: 71, departamentoId: 28, name: ' San Joaquín ' },
    { id: 72, departamentoId: 28, name: ' San José de Miranda ' },
    { id: 73, departamentoId: 28, name: ' San Miguel ' },
    { id: 74, departamentoId: 28, name: ' San Vicente de Chucurí ' },
    { id: 75, departamentoId: 28, name: ' Santa Bárbara ' },
    { id: 76, departamentoId: 28, name: ' Santa Helena del Opón ' },
    { id: 77, departamentoId: 28, name: ' Simacota ' },
    { id: 78, departamentoId: 28, name: ' Socorro ' },
    { id: 79, departamentoId: 28, name: ' Suaita ' },
    { id: 80, departamentoId: 28, name: ' Sucre ' },
    { id: 81, departamentoId: 28, name: ' Suratá ' },
    { id: 82, departamentoId: 28, name: ' Tona ' },
    { id: 83, departamentoId: 28, name: ' Valle de San José ' },
    { id: 84, departamentoId: 28, name: ' Vélez ' },
    { id: 85, departamentoId: 28, name: ' Vetas ' },
    { id: 86, departamentoId: 28, name: ' Villanueva ' },
    { id: 87, departamentoId: 28, name: ' Zapatoca ' },


    { id: 1, departamentoId: 29, name: ' Guaranda ' },
    { id: 2, departamentoId: 29, name: ' Majagual ' },
    { id: 3, departamentoId: 29, name: ' Sucre ' },
    { id: 4, departamentoId: 29, name: ' Chalán ' },
    { id: 5, departamentoId: 29, name: ' Colosó ' },
    { id: 6, departamentoId: 29, name: ' Morroa ' },
    { id: 7, departamentoId: 29, name: ' Ovejas ' },
    { id: 8, departamentoId: 29, name: ' Sincelejo ' },
    { id: 9, departamentoId: 29, name: ' Coveñas ' },
    { id: 10, departamentoId: 29, name: ' Palmito ' },
    { id: 11, departamentoId: 29, name: ' San Onofre ' },
    { id: 12, departamentoId: 29, name: ' Santiago de Tolú ' },
    { id: 13, departamentoId: 29, name: ' Toluviejo ' },
    { id: 14, departamentoId: 29, name: ' Buenavista ' },
    { id: 15, departamentoId: 29, name: ' Corozal ' },
    { id: 16, departamentoId: 29, name: ' El Roble ' },
    { id: 17, departamentoId: 29, name: ' Galeras ' },
    { id: 18, departamentoId: 29, name: ' Los Palmitos ' },
    { id: 19, departamentoId: 29, name: ' Sampués ' },
    { id: 20, departamentoId: 29, name: ' San Juan de Betulia ' },
    { id: 21, departamentoId: 29, name: ' San Pedro ' },
    { id: 22, departamentoId: 29, name: ' Sincé ' },
    { id: 23, departamentoId: 29, name: ' Caimito ' },
    { id: 24, departamentoId: 29, name: ' La Unión ' },
    { id: 25, departamentoId: 29, name: ' San Benito Abad ' },
    { id: 26, departamentoId: 29, name: ' San Marcos ' },


    { id: 1, departamentoId: 30, name: ' Alvarado ' },
    { id: 2, departamentoId: 30, name: ' Anzoátegui ' },
    { id: 3, departamentoId: 30, name: ' Cajamarca ' },
    { id: 4, departamentoId: 30, name: ' Coello ' },
    { id: 5, departamentoId: 30, name: ' El Espinal ' },
    { id: 6, departamentoId: 30, name: ' Flandes ' },
    { id: 7, departamentoId: 30, name: ' Ibagué ' },
    { id: 8, departamentoId: 30, name: ' Piedras ' },
    { id: 9, departamentoId: 30, name: ' Rovira ' },
    { id: 10, departamentoId: 30, name: ' San Luis ' },
    { id: 11, departamentoId: 30, name: ' Valle de San Juan ' },
    { id: 12, departamentoId: 30, name: ' Casabianca ' },
    { id: 13, departamentoId: 30, name: ' Herveo ' },
    { id: 14, departamentoId: 30, name: ' Lérida ' },
    { id: 15, departamentoId: 30, name: ' Líbano ' },
    { id: 16, departamentoId: 30, name: ' Murillo ' },
    { id: 17, departamentoId: 30, name: ' Santa Isabel ' },
    { id: 18, departamentoId: 30, name: ' Venadillo ' },
    { id: 19, departamentoId: 30, name: ' Villahermosa ' },
    { id: 20, departamentoId: 30, name: ' Ambalema ' },
    { id: 21, departamentoId: 30, name: ' Guayabal ' },
    { id: 22, departamentoId: 30, name: ' Falan ' },
    { id: 23, departamentoId: 30, name: ' Fresno ' },
    { id: 24, departamentoId: 30, name: ' Honda ' },
    { id: 25, departamentoId: 30, name: ' San Sebastián de Mariquita ' },
    { id: 26, departamentoId: 30, name: ' Palocabildo ' },
    { id: 27, departamentoId: 30, name: ' Carmen de Apicalá ' },
    { id: 28, departamentoId: 30, name: ' Cunday ' },
    { id: 29, departamentoId: 30, name: ' Icononzo ' },
    { id: 30, departamentoId: 30, name: ' Melgar ' },
    { id: 31, departamentoId: 30, name: ' Villarrica ' },
    { id: 32, departamentoId: 30, name: ' Ataco ' },
    { id: 33, departamentoId: 30, name: ' Chaparral ' },
    { id: 34, departamentoId: 30, name: ' Coyaima ' },
    { id: 35, departamentoId: 30, name: ' Natagaima ' },
    { id: 36, departamentoId: 30, name: ' Ortega ' },
    { id: 37, departamentoId: 30, name: ' Planadas ' },
    { id: 38, departamentoId: 30, name: ' Rioblanco ' },
    { id: 39, departamentoId: 30, name: ' Roncesvalles ' },
    { id: 40, departamentoId: 30, name: ' San Antonio ' },
    { id: 41, departamentoId: 30, name: ' Alpujarra ' },
    { id: 42, departamentoId: 30, name: ' Dolores ' },
    { id: 43, departamentoId: 30, name: ' Guamo ' },
    { id: 44, departamentoId: 30, name: ' Prado ' },
    { id: 45, departamentoId: 30, name: ' Purificación ' },
    { id: 46, departamentoId: 30, name: ' Saldaña ' },
    { id: 47, departamentoId: 30, name: ' Suárez ' },


    { id: 1, departamentoId: 31, name: ' Alcalá ' },
    { id: 2, departamentoId: 31, name: ' Andalucía ' },
    { id: 3, departamentoId: 31, name: ' Ansermanuevo ' },
    { id: 4, departamentoId: 31, name: ' Argelia ' },
    { id: 5, departamentoId: 31, name: ' Bolívar ' },
    { id: 6, departamentoId: 31, name: ' Buenaventura ' },
    { id: 7, departamentoId: 31, name: ' Buga ' },
    { id: 8, departamentoId: 31, name: ' Bugalagrande ' },
    { id: 9, departamentoId: 31, name: ' Caicedonia ' },
    { id: 10, departamentoId: 31, name: ' Cali ' },
    { id: 11, departamentoId: 31, name: ' Calima - El Darién ' },
    { id: 12, departamentoId: 31, name: ' Candelaria ' },
    { id: 13, departamentoId: 31, name: ' Cartago ' },
    { id: 14, departamentoId: 31, name: ' Dagua ' },
    { id: 15, departamentoId: 31, name: ' El Águila ' },
    { id: 16, departamentoId: 31, name: ' El Cairo ' },
    { id: 17, departamentoId: 31, name: ' El Cerrito ' },
    { id: 18, departamentoId: 31, name: ' El Dovio ' },
    { id: 19, departamentoId: 31, name: ' Florida ' },
    { id: 20, departamentoId: 31, name: ' Ginebra ' },
    { id: 21, departamentoId: 31, name: ' Guacarí ' },
    { id: 22, departamentoId: 31, name: ' Jamundí ' },
    { id: 23, departamentoId: 31, name: ' La Cumbre ' },
    { id: 24, departamentoId: 31, name: ' La Unión ' },
    { id: 25, departamentoId: 31, name: ' La Victoria ' },
    { id: 26, departamentoId: 31, name: ' Obando ' },
    { id: 27, departamentoId: 31, name: ' Palmira ' },
    { id: 28, departamentoId: 31, name: ' Pradera ' },
    { id: 29, departamentoId: 31, name: ' Restrepo ' },
    { id: 30, departamentoId: 31, name: ' Riofrío ' },
    { id: 31, departamentoId: 31, name: ' Roldanillo ' },
    { id: 32, departamentoId: 31, name: ' San Pedro ' },
    { id: 33, departamentoId: 31, name: ' Sevilla ' },
    { id: 34, departamentoId: 31, name: ' Toro ' },
    { id: 35, departamentoId: 31, name: ' Trujillo ' },
    { id: 36, departamentoId: 31, name: ' Tuluá ' },
    { id: 37, departamentoId: 31, name: ' Ulloa ' },
    { id: 38, departamentoId: 31, name: ' Versalles ' },
    { id: 39, departamentoId: 31, name: ' Vijes ' },
    { id: 40, departamentoId: 31, name: ' Yotoco ' },
    { id: 41, departamentoId: 31, name: ' Yumbo ' },
    { id: 42, departamentoId: 31, name: ' Zarzal ' },


    { id: 1, departamentoId: 32, name: ' Carurú ' },
    { id: 2, departamentoId: 32, name: ' Mitú ' },
    { id: 3, departamentoId: 32, name: ' Pacoa ' },
    { id: 4, departamentoId: 32, name: ' Papunaua ' },
    { id: 5, departamentoId: 32, name: ' Taraira ' },
    { id: 6, departamentoId: 32, name: ' Yavaraté ' },


    { id: 1, departamentoId: 33, name: ' Cumaribo ' },
    { id: 2, departamentoId: 33, name: ' La Primavera ' },
    { id: 3, departamentoId: 33, name: ' Puerto Carreño ' },
    { id: 4, departamentoId: 33, name: ' Santa Rosalía ' }
  ]

  getDepartamentos(): DepartamentoI[] {
    return this.departamentos;
  }

  getCiudades(): CiudadI[] {
    return this.ciudades;
  }

}


